### model
model_name_or_path: /mnt/luoyingfeng/model_card/Meta-Llama-3.2-1B
#trust_remote_code: true
template: llama3
### method
stage: pt
do_train: true
finetuning_type: full

### dataset
dataset_dir: /mnt/luoyingfeng/lora4mt/data/fine-tuning_data/cpt_data
dataset: cpt-kk-en
cutoff_len: 512
use_fast_tokenizer: true
dataloader_num_workers: 8
preprocessing_num_workers: 16

### output
output_dir: /mnt/luoyingfeng/lora4mt/exps/Meta-Llama-3.2-1B/fft_cpt
logging_steps: 0.01
save_steps: 0.05
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 2.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
seed: 42
save_strategy: steps
logging_strategy: steps

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500